require 'spec_helper'

def required_attributes
  {:description => "something", :user_id => 1}
end

describe Token do
  before(:each) do
    @token = Token.create!(required_attributes)
  end
  
  describe "name generation" do
    it "should be created with an autogenerated name" do
      @token.name.should_not be_empty
    end
  
    it "should not autogenerate a name when loading a saved record" do
      Token.first.name.should == @token.name
    end
  end
  
  it "should be created with no visits" do
    @token.visits.count.should == 0
  end
end
